### ISSUE TITLE
Port hidata4socet.pl to Python

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/APPL-Tools#58]
In order to more readily support HiRISE projects in Socet Set/Socet GXP that are set up against the IAU sphere, rather than a biaxial ellipsoid, it would be beneficial to update the legacy [hidata4socet.pl](https://github.com/USGS-Astrogeology/socet_set/blob/master/SS4HiRISE/Software/ISIS3_MACHINE/PERL_SCRIPTS/hidata4socet.pl) script to extract MOLA products (gridded and shot data) with heights relative to a sphere rather than relative to the geoid as is currently the case.

It would make sense to port the general functionality of the legacy script from Perl to Python.

**Comment by thareUSGS** [comment]
I think the only function we really need from hidata2socet.pl is upsampling 256ppd and cropping MOLA for the intended area  (now with heights relative to a sphere).  If this run a raster crop and MOLA shot python script (hitting ODE) in one routine, I am fine with that). But I could see that being two runs also (shots, grid).  

Anyway a simple helper script to output a GeoTIFF in degrees (or polar), I think we can skip output to ASCII raster for now (although it might be a simple GDAL output option). If you think of a way to use a single script to help with LOLA, etc. , that would be nice.

**Comment by dpmayerUSGS** [comment]
@thareUSGS Does GXP have any special requirements for reading GeoTIFFs? I recall that Socet Set used some esoteric (and proprietary) tags that made it difficult for planetary data.

**Comment by thareUSGS** [comment]
Just re-tested for import. You do need to explicitly import as a "terrain", otherwise it loads as an image.  Even if a GCS is defined it will generally make you redefine it (gives you the option to overwrite the internal header or create a new version). But there could still some oddities like support for the defined NoDATA, so I guess we may need the ASCII import as a fallback (by using -of AAIGrid ).
