### ISSUE TITLE
GPX gpf uses degrees not radians

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/APPL-Tools#69]
For https://github.com/USGS-Astrogeology/APPL-Tools/blob/master/SurfaceFit/surface_fit_pc_align.py I realized that GXP gpfs default to using degrees not radians. This might complicate this issue: https://github.com/USGS-Astrogeology/APPL-Tools/issues/68

As a temporary fix in surface_fit_pc_align.py I updated these four lines to not do any radian/degree conversions...

```
if not s_srs:
        tp_df.lat_Y_North = np.degrees(tp_df.lat_Y_North)
        tp_df.long_X_East = ((360 + np.degrees(tp_df.long_X_East)) % 360)
```
to
```
if not s_srs:     
        ##  tp_df.lat_Y_North = np.degrees(tp_df.lat_Y_North)
        tp_df.long_X_East = ((360 + (tp_df.long_X_East)) % 360)
```
and

```
if not s_srs:      
      tp_df.lat_Y_North = np.radians(tp_df['lat_Y_North'])        
      tp_df.long_X_East = np.radians(((tp_df['long_X_East'] + 180) % 360) - 180)
```
to
```
if not s_srs:        
        ## tp_df.lat_Y_North = np.radians(tp_df['lat_Y_North'])
        tp_df.long_X_East = (((tp_df['long_X_East'] + 180) % 360) - 180)
```

So perhaps to handle turning off any radian/degree conversions and the issue https://github.com/USGS-Astrogeology/APPL-Tools/issues/68 , maybe a "--gxp" flag can be used in surface_fit_pc_align.py?

**Comment by dpmayerUSGS** [comment]
@thareUSGS The presence of degrees rather than radians in the GPF doesn't break the current functionality. You can use the existing `--s_srs` option to specify a PROJ string that describes a geographic coordinate system in degrees. I added that option to handle cases where the GPF may use a projected coordinate system (as is standard practice for polar stereopairs), but it will work just fine for lat/lon if you pass an appropriate PROJ string.
